### ISSUE TITLE
errrrrnnnnn

### ISSUE THREAD

**Issue by Ianyourgod** [Saturn-VI/netbackground#1]
why is it not written in c...............................................................................

**Comment by Saturn-VI** [comment]
die

**Comment by Saturn-VI** [comment]
I retract my original statement and instead wish you to "quit yapping", as the kids say.

**Comment by Ianyourgod** [comment]
as the would kids would say, its all over the screen fellas!!! 😃😃 Datebyo!!

**Comment by Saturn-VI** [comment]
You've fallen off more than the guys on the Francis Scott Key bridge
